# Generated by Django 5.2.1 on 2025-06-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код специальности')),
                ('name', models.CharField(max_length=50, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность врача',
                'verbose_name_plural': 'Специальности врачей',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код услуги')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Врач')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.doctorspeciality', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Связь врача и специальности',
                'verbose_name_plural': 'Связи врачей и специальностей',
                'unique_together': {('doctor', 'speciality')},
            },
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Врач')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга врача',
                'verbose_name_plural': 'Услуги врачей',
                'unique_together': {('service', 'doctor')},
            },
        ),
    ]
