# Generated by Django 5.2.1 on 2025-06-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код клиники')),
                ('name', models.CharField(max_length=254, verbose_name='Название клиники')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('working_hours', models.CharField(max_length=50, verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('note', models.CharField(max_length=100, verbose_name='Примечание')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
