# Generated by Django 5.2.1 on 2025-06-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisName',
            fields=[
                ('analysis_name_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код названия анализа')),
                ('name', models.CharField(max_length=100, verbose_name='Название анализа')),
            ],
            options={
                'verbose_name': 'Название анализа',
                'verbose_name_plural': 'Названия анализов',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisName',
            fields=[
                ('diagnosis_name_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код названия диагноза')),
                ('name', models.CharField(max_length=50, verbose_name='Название диагноза')),
            ],
            options={
                'verbose_name': 'Название диагноза',
                'verbose_name_plural': 'Названия диагнозов',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код анализа')),
                ('result', models.CharField(blank=True, max_length=500, verbose_name='Результат')),
                ('analysis_date', models.DateField(verbose_name='Дата анализа')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Пациент')),
                ('analysis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.analysisname', verbose_name='Название анализа')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код диагноза')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Прием')),
                ('diagnosis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.diagnosisname', verbose_name='Название диагноза')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
    ]
